apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "19"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"xfinder-frontend","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"xfinder-frontend"}},"template":{"metadata":{"labels":{"app":"xfinder-frontend"}},"spec":{"containers":[{"env":[{"name":"VITE_API_URL","value":"http://xfinder-api:5000"}],"image":"ethans333/xfinder-frontend:latest","imagePullPolicy":"IfNotPresent","name":"xfinder-frontend","ports":[{"containerPort":80}]}]}}}}
  creationTimestamp: "2025-07-14T22:16:20Z"
  generation: 19
  name: xfinder-frontend
  namespace: default
  resourceVersion: "22802"
  uid: 2c80d208-862c-4a59-b55f-228f55e7132b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: xfinder-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-07-15T08:33:55-04:00"
      creationTimestamp: null
      labels:
        app: xfinder-frontend
    spec:
      containers:
      - env:
        - name: VITE_API_URL
          value: http://xfinder-api:5000
        image: ethans333/xfinder-frontend:latest
        imagePullPolicy: IfNotPresent
        name: xfinder-frontend
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-07-15T12:29:47Z"
    lastUpdateTime: "2025-07-15T12:29:47Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-07-14T22:26:25Z"
    lastUpdateTime: "2025-07-15T12:33:57Z"
    message: ReplicaSet "xfinder-frontend-cc7db88b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 19
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
