apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  POSTGRES_HOST: db
  POSTGRES_DATABASE_URL: postgresql://postgres:password@xfinder-postgres:5432/xfinderdb
